# -*- coding: utf-8 -*-
"""Manual2Skill_Demo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15XH8jhqodE4-GuiIe_IRrwjaeZt6uiQj

Copyright 2025 NUS. SPDX-License-Identifier: Apache-2.0

<details>
<summary>Click to expand</summary>

Copyright 2025 NUS. SPDX-License-Identifier: Apache-2.0

Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
</details>

# **Manual2Skill: Learning to Read Manuals and Acquire Robotic Skills for Furniture Assembly Using Vision-Language Models**

## **Demo for VLM-Guided Hierachical Assembly Graph Generation**

[Manual2Skill](https://owensun2004.github.io/Furniture-Assembly-Web/) is a novel framework that enables robots to autonomously perform complex assembly tasks in real-life by learning from high-level manual instructions.

This Colab notebook demonstrates the first process of Manual2Skill: **1. VLM-Guided Hierarchical Graph Generation**. Specifically, it includes the prompts (Image Sets & Text Instructions) and API calls for Stages I & II, which the VLM uses to generate a predicted and visualized Assembly Graph, along with intermediate non-visualized outputs. Overall, this notebook illustrates the ability of VLMs to reason about IKEA manual images and produce accurate assembly plans.

<img src="https://owensun2004.github.io/Furniture-Assembly-Web/static/images/pipeline.png" height="500px">

**Model Selection Disclaimer:** This demo uses gpt-4o-2024-11-20, the tested version. Our experiments indicate that GPT-4o performs reasonably well for simple to moderate furniture items with <= 6 furniture parts, but struggles with more complex assemblies involving >= 7 furniture parts. While other VLM models may be used, their performance has not been evaluated.
"""

import os
os.environ["OPENAI_API_KEY"] = "your-api-key"

"""## **Setup**"""

#@markdown A few imports
!pip install openai==1.55.3 httpx==0.27.2 --force-reinstall --quiet

import ast
import json
import os
import re
import base64
import copy
import matplotlib.pyplot as plt
from openai import OpenAI

#@markdown Clone the repository for all the 102 furniture items from the IKEA-Manuals dataset and their corresponding data
!git clone https://github.com/owensun2004/Furniture_Assembly.git

"""## **Specify the furniture**
Please select the furniture for the VLM to plan for assembly.

<details>
<summary>Click to see examples</summary>

furniture_name = "applaro"

furniture_type = "Bench"

OR

furniture_name = "voxlov"

furniture_type = "Chair"
</details>

<details>
<summary>Click to view guidelines for accessing the full list of 102 available furniture names and types.</summary>


The furniture type includes "Bench", "Chair", "Desk", "Misc", "Shelf", and "Table". These types are located under the github repo you just cloned to this Colab notebook: Furniture_Assembly/IKEA-Manuals-at-Work/data/{dir}/, where {dir} is any of mask, parts, pdfs. Under each furniture type directory, you can find the furniture name.
</details>

"""

furniture_name = "" #@param {type:"string"}
furniture_type = "" #@param {type:"string"}

"""## **Stage I: Associating Real Parts with Manuals**
The VLM uses Stage I Image Set input, along with Stage I Text Instructions, to generate connections between parts in the pre-assembly scene and parts drawn on the manual, represented as JSON.

Unlike the Image Set, the Text Instructions are consistent across all furniture items. For previews of the Text Instructions, see Appendix K of our [paper](https://arxiv.org/pdf/2502.10090).
"""

#@markdown Preview of Stage I Image Set Input
from IPython.display import display
from PIL import Image

# Load images
image1 = Image.open(f"Furniture_Assembly/IKEA-Manuals-at-Work/output/{furniture_type}/{furniture_name}/scene_annotated.png")
image2 = Image.open(f"Furniture_Assembly/IKEA-Manuals-at-Work/data/pdfs/{furniture_type}/{furniture_name}/page_1.png")

fig, axes = plt.subplots(1, 2, figsize=(15, 5))

# Display images in subplots
axes[0].imshow(image1)
axes[0].axis('off')  # Hide axes
axes[1].imshow(image2)
axes[1].axis('off')

plt.show()

#@markdown VLM API Calls for Stage I
def alphanumeric_sort_key(filename):
    # Split the filename into a list of alphabetic and numeric parts
    return [int(text) if text.isdigit() else text for text in re.split(r'(\d+)', filename)]

def select_materials_for_planning(furniture_name, furniture_type, temp):
    scene_path = f"Furniture_Assembly/IKEA-Manuals-at-Work/output/{furniture_type}/{furniture_name}/scene_annotated.png"
    manual_path = f"Furniture_Assembly/IKEA-Manuals-at-Work/data/pdfs/{furniture_type}/{furniture_name}/page_1.png"
    json_text = generate_json(scene_path, manual_path, 0)

    prompt_text = "select_material"

    def encode_image(image_path):
        with open(image_path, "rb") as image_file:
            return base64.b64encode(image_file.read()).decode('utf-8')

    b64_pages = []
    for page in os.listdir(f"Furniture_Assembly/IKEA-Manuals-at-Work/data/pdfs/{furniture_type}/{furniture_name}/"):
        if page.endswith(".png"):
            page_path = os.path.join(f"Furniture_Assembly/IKEA-Manuals-at-Work/data/pdfs/{furniture_type}/{furniture_name}/", page)
            b64_pages.append(encode_image(page_path))

    b64_pages_sorted = sorted(b64_pages, key=alphanumeric_sort_key)
    base64_image = encode_image(scene_path)

    client = OpenAI()

    with open(f"Furniture_Assembly/furniture_assembly/prompts/{prompt_text}.txt", 'r') as f:
        prompt = f.read()

    # Build the dynamic list of image messages based on the number of pages
    image_messages = [
        {
            "type": "image_url",
            "image_url": {
                "url": f"data:image/jpeg;base64,{base64_image}",
                "detail": "high"
            },
        }
    ]

    # Add each page image to the message
    for i, b64_image in enumerate(b64_pages_sorted):
        image_messages.append({
            "type": "image_url",
            "image_url": {
                "url": f"data:image/jpeg;base64,{b64_image}",
                "detail": "high"
            },
        })

    response = client.chat.completions.create(
        model="gpt-4o-2024-11-20",
        messages=[
            {
                "role": "user",
                "content": [
                    {"type": "text", "text": prompt + "\n\nAnd here is the json file: \n" + json_text},
                    *image_messages  # Unpack the dynamic list of image messages
                ],
            }
        ],
        max_tokens=1000,
        temperature = temp
    )

    input_prompt = prompt + "\n\nAnd here is the json file: \n" + json_text

    return input_prompt, response.choices[0].message.content

def generate_json(img_path, manual_path, temp):
    def encode_image(image_path):
        with open(image_path, "rb") as image_file:
            return base64.b64encode(image_file.read()).decode('utf-8')

    base64_image = encode_image(img_path)
    base64_image2 = encode_image(manual_path)
    with open("Furniture_Assembly/furniture_assembly/prompts/generate_json.txt", 'r') as f:
        prompt = f.read()
    client = OpenAI()
    response = client.chat.completions.create(
        model="gpt-4o-2024-11-20",
        messages=[
            {
                "role": "user",
                "content": [
                    {"type": "text", "text": prompt},
                    {
                        "type": "image_url",
                        "image_url": {
                            "url": f"data:image/png;base64,{base64_image}",
                            "detail": "high"
                        }
                    },
                    {
                        "type": "image_url",
                        "image_url": {
                            "url": f"data:image/png;base64,{base64_image2}",
                            "detail": "high"
                        }
                    },
                ],
            }
        ],
        max_tokens=1000,
        temperature=temp,
    )
    final_output = response.choices[0].message.content.replace("```json", "").replace("```", "")
    return final_output


input_prompt, output_table = select_materials_for_planning(furniture_name, furniture_type, 0)
print("========== Stage I: Output ===========")
print(output_table.replace("```json", "").replace("```", ""))

"""## **Stage II: Identify Involved Parts in Each Step**
The VLM uses Stage I JSON output, Stage II Image Set input, and Stage II Text Instructions input to generate a text-based assembly plan.
"""

#@markdown Preview of Stage II Image Set Input
file_list = os.listdir(f"Furniture_Assembly/IKEA-Manuals-at-Work/data/mask/{furniture_type}/{furniture_name}/")
sorted_file_list = sorted(file_list, key=alphanumeric_sort_key)

final_list = []
for filename in sorted_file_list:
    if filename.endswith("no_seg_numbered.png"):
      final_list.append(os.path.join(f"Furniture_Assembly/IKEA-Manuals-at-Work/data/mask/{furniture_type}/{furniture_name}/", filename))

num_images = len(final_list)

# Calculate the number of rows and columns for the grid
cols = 3  # Number of columns (you can adjust this)
rows = (num_images + cols - 1) // cols  # Calculate rows dynamically

# Create a figure and subplots
fig, axes = plt.subplots(rows, cols, figsize=(15, 5 * rows))

# Flatten axes if there's only one row
if rows == 1:
    axes = axes.reshape(1, -1)

# Display images in subplots
for i, image_path in enumerate(final_list):
    img = Image.open(image_path)
    row = i // cols
    col = i % cols
    axes[row, col].imshow(img)
    axes[row, col].axis('off')  # Hide axes

# Hide empty subplots if the number of images is not a multiple of cols
for i in range(num_images, rows * cols):
    row = i // cols
    col = i % cols
    axes[row, col].axis('off')

plt.tight_layout()
plt.show()

#@markdown VLM API Calls for Stage II
def create_plan(furniture_name, furniture_type, temp):
    prompt_text = "planning_no_seg"

    def encode_image(image_path):
        with open(image_path, "rb") as image_file:
            return base64.b64encode(image_file.read()).decode('utf-8')

    # Encode the main labeled image
    image_path = f"Furniture_Assembly/IKEA-Manuals-at-Work/output/{furniture_type}/{furniture_name}/scene_annotated.png"
    base64_image = encode_image(image_path)

    # Initialize OpenAI client
    client = OpenAI()

    # Load prompt text
    with open(f"Furniture_Assembly/furniture_assembly/prompts/{prompt_text}.txt", 'r') as f:
        prompt = f.read()

    prompt = prompt + output_table

    # Encode 3D OBJ images
    obj_img = []
    file_list = os.listdir(f"Furniture_Assembly/IKEA-Manuals-at-Work/data/pdfs/{furniture_type}/{furniture_name}/")
    file_list = os.listdir(f"Furniture_Assembly/IKEA-Manuals-at-Work/data/mask/{furniture_type}/{furniture_name}/")
    sorted_file_list = sorted(file_list, key=alphanumeric_sort_key)


    for filename in sorted_file_list:
        if filename.endswith("no_seg_numbered.png"):
            img_path = os.path.join(f"Furniture_Assembly/IKEA-Manuals-at-Work/data/mask/{furniture_type}/{furniture_name}/", filename)
            obj_img.append(
                encode_image(img_path)
            )
    image_messages = [
        {
            "type": "image_url",
            "image_url": {
                "url": f"data:image/jpeg;base64,{base64_image}",
                "detail": "high"
            },
        }
    ]
    for b64_obj_image in obj_img:
        image_messages.append({
            "type": "image_url",
            "image_url": {
                "url": f"data:image/jpeg;base64,{b64_obj_image}",
                "detail": "high"
            },
        })

    response = client.chat.completions.create(
        model="gpt-4o-2024-11-20",
        messages=[
            {
                "role": "user",
                "content": [
                    {"type": "text", "text": prompt},
                    *image_messages
                ],
            }
        ],
        max_tokens=1000,
        temperature=temp,
    )
    return response.choices[0].message.content, prompt

output_plan, planning_prompt = create_plan(furniture_name, furniture_type, 0)
print("========== Stage II: Output ===========")
print(output_plan)

"""## **Convert text-based assembly plan to Hierachical Assembly Graph**
The converted graph is stored in a nested list, enabling easier comparison with the ground truth assembly graph and downstream graph visualization.

Please refer to Section V-A of our [paper](https://arxiv.org/pdf/2502.10090) to see detailed explanations of assembly graph evaluations.
"""

#@markdown
from itertools import permutations

def print_trees(tree, nested_list, holder):
    if not nested_list:
        return
    ele = nested_list[0]
    l = list(permutations(ele))  # Generate permutations for the current list
    pointer_dict = {}

    for i, e in enumerate(ele):
        path = find_position(tree, e)
        if path is None:
            pointer_dict["pt" + str(i)] = None  # Mark as None if not found
        else:
            pointer_str = f"tree{''.join([f'[{idx}]' for idx in path])}"
            pointer_dict["pt" + str(i)] = pointer_str

    for perm in l:
        skip = False
        for j, val in enumerate(perm):
            key = f"pt{j}"
            if pointer_dict[key] is None:  # Skip if any value is missing
                skip = True
                break
            exec(f"{pointer_dict[key]} = {val}")

        if not skip:
            holder.append(eval(repr(tree)))  # Use eval(repr(...)) to deep copy

        # Continue the recursion
        print_trees(tree, nested_list[1:], holder)


def find_position(tree, target, path=None):
    """
    Recursively finds the path to the target in a nested list.
    """
    if path is None:
        path = []
    if isinstance(tree, list):
        for i, item in enumerate(tree):
            new_path = path + [i]
            if item == target:
                return new_path
            elif isinstance(item, list):
                result = find_position(item, target, new_path)
                if result is not None:
                    return result
    return None


def convert_to_tree(furniture_name, furniture_type, temp):

  prompt_text = "tree_ikea_manual"

  client = OpenAI()

  with open(f"Furniture_Assembly/furniture_assembly/prompts/{prompt_text}.txt", 'r') as f:
      prompt = f.read()

  prompt = prompt + "\n" + output_plan + "\n\nYOUR REAL OUTPUT:\n"


  response = client.chat.completions.create(
    model="gpt-4o-2024-11-20",
    messages=[
      {
        "role": "user",
        "content": [
          {"type": "text", "text": prompt}
        ],
      }
    ],
    max_tokens=2000,
    temperature = temp,
  )

  final_output = response.choices[0].message.content.replace("```python", "").replace("```", "")
  return final_output

def load_paths(json_path):
  """Load directory paths from the JSON file."""
  with open(json_path, 'r') as f:
      data = json.load(f)
  return data

def compare_to_gt_tree(furniture_name, furniture_type):
  json_file_path = "Furniture_Assembly/IKEA-Manuals-at-Work/data/main_data.json"

  data = load_paths(json_file_path)

  for i in range(len(data)):
    cur_furniture_name = data[i]["name"]
    cur_furniture_category = data[i]["category"]
    if cur_furniture_name == furniture_name and cur_furniture_category == furniture_type:
      return data[i]["assembly_tree"], data[i]["parts_ct"]

  return "Error: No ground truth assembly tree found, check if furniture name and furniture type are inputted correctly"

def are_nested_lists_equal(list1, list2):
    # Create deep copies of the lists to avoid modifying the originals
    list1_copy = copy.deepcopy(list1)
    list2_copy = copy.deepcopy(list2)

    # If both are not lists, compare directly
    if not isinstance(list1_copy, list) or not isinstance(list2_copy, list):
        return list1_copy == list2_copy

    # If lengths are different, they can't be equal
    if len(list1_copy) != len(list2_copy):
        return False

    # Recursively check each element in the lists
    for item1 in list1_copy:
        found_match = False
        for item2 in list2_copy:
            if are_nested_lists_equal(item1, item2):
                found_match = True
                list2_copy.remove(item2)  # Remove the matched item to avoid re-matching
                break
        if not found_match:
            return False

    return True

def evaluate_tree(final_tree, gt_tree, num_parts):
  if are_nested_lists_equal(final_tree, gt_tree):
    return True
  with open(f"Furniture_Assembly/IKEA-Manuals-at-Work/output/{furniture_type}/{furniture_name}/equiv_parts.txt", "r") as text_file:
      data = text_file.read()
  nest_list = ast.literal_eval(data)
  tree_store = []
  print_trees(copy.deepcopy(final_tree), nest_list, tree_store)
  for indiv_tree in tree_store:
      if num_parts>=11:
          break
      if are_nested_lists_equal(indiv_tree, gt_tree):
          return True
  return False


final_tree_str = convert_to_tree(furniture_name, furniture_type, 0)
final_tree = ast.literal_eval(final_tree_str)
print(f"VLM predicted assembly graph: {final_tree}")
gt_tree, num_parts = compare_to_gt_tree(furniture_name, furniture_type)
print(f"Ground truth assembly graph: {gt_tree}")

flag = evaluate_tree(final_tree, gt_tree, num_parts)
print(f"\n\nAssembly Graph Evaluation:\nIs the predicted graph equal to the ground truth graph: {flag}")

"""## **Visualize Assembly Graph**

This visualization allows us to easily see whether the predicted assembly graph is physically feasible.

Leaf nodes in the IKEA-Manuals dataset are stored as obj files. For display purposes, we converted them to png format, which may appear less refined compared to the non-leaf nodes (manual pages) that are already in png format.
"""

#@markdown Install required packages
!pip install networkx IPython trimesh pyrender pyglet
!apt-get install -y xvfb libgl1-mesa-glx

# Set up a virtual display
import os
os.system('Xvfb :1 -screen 0 1600x1200x16 &')  # Start virtual display
os.environ['DISPLAY'] = ':1'  # Tell rendering tools to use this display

import trimesh
import pyrender
import numpy as np
from PIL import Image

def render_obj_to_png(obj_path, png_path):
    """Render OBJ files that might contain scenes or multiple meshes"""
    try:
        # Load the OBJ file
        scene_or_mesh = trimesh.load(obj_path)

        # Create pyrender scene
        scene = pyrender.Scene()

        # Handle both single meshes and scenes
        if isinstance(scene_or_mesh, trimesh.Scene):
            # Convert all meshes in the scene
            for geom in scene_or_mesh.geometry.values():
                if isinstance(geom, trimesh.Trimesh):
                    mesh = pyrender.Mesh.from_trimesh(geom)
                    scene.add(mesh)
        else:
            # Handle single mesh case
            mesh = pyrender.Mesh.from_trimesh(scene_or_mesh)
            scene.add(mesh)

        # Configure camera (adjusted for better viewing)
        camera = pyrender.PerspectiveCamera(yfov=np.pi/3.0, aspectRatio=1.0)
        camera_pose = np.eye(4)
        camera_pose[:3, 3] = [0, 0, 2.5]  # Increased camera distance
        scene.add(camera, pose=camera_pose)

        # Add directional light
        light = pyrender.DirectionalLight(color=[1,1,1], intensity=5.0)
        scene.add(light, pose=np.eye(4))

        # Render and save
        renderer = pyrender.OffscreenRenderer(800, 800)
        color, _ = renderer.render(scene)
        Image.fromarray(color).save(png_path)
        renderer.delete()

    except Exception as e:
        print(f"Failed to render {obj_path}: {type(e).__name__} - {str(e)}")

#@markdown Visualize predicted and ground truth assembly graphs
import networkx as nx
import os
from matplotlib.offsetbox import OffsetImage, AnnotationBbox
from PIL import Image
from IPython.display import display

class TreeNode:
    def __init__(self, name, id, image=None):
        self.name = name
        self.id = id
        self.children = []
        self.image = image

def build_tree(nested_list, png_counter, node_id=[0]):
    if isinstance(nested_list, int):  # Leaf node
        current_id = node_id[0]
        node_id[0] += 1

        # Define paths
        obj_filename = f"{nested_list:02d}.obj"
        png_filename = f"{nested_list:02d}.obj.png"
        obj_path = f"Furniture_Assembly/IKEA-Manuals-at-Work/data/parts/{furniture_type}/{furniture_name}/{obj_filename}"
        png_path = f"Furniture_Assembly/IKEA-Manuals-at-Work/data/parts/{furniture_type}/{furniture_name}/{png_filename}"

        # Generate PNG if missing
        if not os.path.exists(png_path):
            if os.path.exists(obj_path):
                render_obj_to_png(obj_path, png_path)
            else:
                print(f"Missing OBJ: {obj_path}")
                png_path = None  # Fallback

        return TreeNode(name=f"Leaf_{nested_list}", id=current_id, image=png_path)

    children = [build_tree(child, png_counter, node_id) for child in nested_list]

    node = TreeNode(
        name=f"NonLeaf_{node_id[0]}",
        id=node_id[0],
        image=f"Furniture_Assembly/IKEA-Manuals-at-Work/data/mask/{furniture_type}/{furniture_name}/step_{png_counter[0]}_no_seg_numbered.png"
    )
    png_counter[0] += 1
    node_id[0] += 1  # Increment unique ID counter
    node.children = children

    return node

def add_edges(graph, node, parent=None, pos={}, level=0, x=0, width=4.0):
    if node:
        pos[node.id] = (x, -level - 2)
        if parent is not None:
            graph.add_edge(parent.id, node.id)

        num_children = len(node.children)
        dx = width
        for i, child in enumerate(node.children):
            add_edges(graph, child, node, pos, level+1, x + (i - num_children / 2) * dx, width)

    return pos

def draw_tree_with_images(root, gt):
    G = nx.DiGraph()
    pos = add_edges(G, root)

    fig, ax = plt.subplots(figsize=(12, 12))
    nx.draw(G, pos, with_labels=True, node_size=6000, ax=ax, arrows=True)

    for node_id, (x, y) in pos.items():
        node = find_node_by_id(root, node_id)
        if node and node.image:
            try:
                if os.path.exists(node.image):
                    img = Image.open(node.image)
                    img = img.resize((50, 50))
                    imagebox = OffsetImage(img, zoom=1)
                    ab = AnnotationBbox(imagebox, (x, y), frameon=False, box_alignment=(0.5, 0.5))
                    ax.add_artist(ab)
                else:
                    print(f"Image not found: {node.image}")
            except Exception as e:
                print(f"Error loading image {node.image}: {e}")

    plt.title(f"{gt} Assembly Graph Visualization Below")
    plt.show()

def find_node_by_id(node, id):
    if node.id == id:
        return node
    for child in node.children:
        found = find_node_by_id(child, id)
        if found:
            return found
    return None

try:
    nested_list = final_tree
    png_counter = [0]  # Counter for non-leaf node images
    root_predicted = build_tree(nested_list, png_counter)
    draw_tree_with_images(root_predicted, "VLM Predicted")
except Exception as e:
    print(f"An error occurred during the visualization of the VLM Predicted Assembly Graph. This likely indicates that the graph deviated significantly from the ground truth assembly graph, resulting in no suitable png/obj files to represent its nodes. Hence, the visualized graph cannot be constructed.\nAdditional error message: {str(e)}")

png_counter_gt = [0]
root_gt = build_tree(gt_tree, png_counter_gt)
draw_tree_with_images(root_gt, "Ground Truth")